import turtle as t
import random as r
#import(c:\Users\Clone Troopers\Downloads\kawaii-background-gif.gif)
#global vars and objects
wn=t.Screen()
#wn.bgpic('c:\Users\Clone Troopers\Downloads\kawaii-background-gif.gif')
wn.bgcolor('skyblue')


def snow(numberOfFlakes,colorOfSnow,farLeft,farRight,upper,lower,speed,variation,ground):
     snowFlakes=[]
     for i in range(numberOfFlakes):
          s=t.Turtle(shape='circle')
          s.color(colorOfSnow)
          s.speed(0)
          s.penup()
          s.goto(r.randint(farLeft,farRight),r.randint(lower,upper))        #r->random module
          snowFlakes.append(s)

     #runningcode
     while True:
          for s in snowFlakes:
               newX=s.xcor()+r.randint(-variation, variation)
               newY=s.ycor()+r.randint(-speed, 0)
               s.goto(newX,newY)
               if s.ycor()<-ground:
                    s.stamp()
                    s.sety(r.randint(lower,upper))

def snowMan(colorOfSnowMan,height):
    w=5
    a=t.Turtle(shape='circle')
    a.color(colorOfSnowMan)
    a.turtlesize(w)
    a.penup()
    a.goto(150,-280)
    for i in range(height):
        a.pendown()
        a.stamp()
        a.penup()
        a.sety((a.ycor())+40)
        w-=1
        a.turtlesize(w)
        
def snowFace():
    a=t.Turtle(shape='circle')
    a.color('black')
    a.turtlesize(.5)
    a.penup()
    a.goto(135,-190)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(165,-190)
    a.pendown()
    a.stamp()
    a.penup()
    a=t.Turtle(shape='triangle')
    a.color('orange')
    a.tilt(-10)
    a.penup()
    a.goto(150,-210)
    a.pendown()
    a.stamp()
    a.penup()
        
def trunkOfTree(colorOfTrunk):
    a=t.Turtle(shape='square')
    a.color(colorOfTrunk)
    a.pensize(100)
    a.penup()
    a.goto(-150,-300)
    a.pendown()
    a.stamp()
    a.penup()
        
def tree(colorOfTree,height):
    w=4
    a=t.Turtle(shape='triangle')
    a.tilt(90)
    a.color(colorOfTree)
    a.turtlesize(w)
    print(a.pensize())
    a.penup()
    a.goto(-150,-280)
    for i in range(height):
        a.pendown()
        a.stamp()
        a.penup()
        a.sety((a.ycor())+30)
        w-=1
        a.turtlesize(w)
        
def present(colorOfPresent,colorOfWrapping):
    a=t.Turtle(shape='square')
    a.turtlesize(3)
    a.color(colorOfPresent)
    a.penup()
    a.goto(0,-280)
    a.pendown()
    a.stamp()
    a.penup()
    a=t.Turtle()
    a.penup()
    a.pensize(3)
    a.color(colorOfWrapping)
    a.goto(-30,-280)
    a.pendown()
    a.goto(30,-280)
    a.penup()
    a.goto(0,-310)
    a.pendown()
    a.goto(0,-250)
    a.penup()
    
def ornaments():
    a=t.Turtle(shape='circle')
    a.turtlesize(.5)
    a.color('red')
    a.penup()
    a.goto(-160,-290)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(-165,-250)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(-150,-230)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(-130,-270)
    a.pendown()
    a.stamp()
    a.penup()

def star():
    a=t.Turtle(shape='triangle')
    a.turtlesize(1)
    a.color('yellow')
    a.penup()
    a.goto(-150,-190)
    a.pendown()
    a.stamp()
    a.penup()
    a.tilt(70)
    a.pendown()
    a.stamp()
    a.penup()
    
def hat():
    a=t.Turtle(shape='square')
    a.turtlesize(2)
    a.color('black')
    a.penup()
    a.goto(150,-155)
    a.pendown()
    a.stamp()
    a.penup()
    a=t.Turtle()
    a.penup()
    a.pensize(4)
    a.color('black')
    a.goto(125,-175)
    a.pendown()
    a.goto(175,-175)
    a.penup()
    a.hideturtle()
    
def text():
    writer=t.Turtle()
    writer.penup()
    writer.goto(-120,0)
    writer.hideturtle()
    writer.color('black')
    writer.write("Merry Christmas!",font=("Verdanan",25,"normal"))  
    writer.penup()  

def angel():
    a=t.Turtle(shape='triangle')
    a.color('white')
    a.turtlesize(4)
    a.penup()
    a.tilt(90)
    a.goto(-300,-205)
    a.pendown()
    a.stamp()
    a.penup()
    a=t.Turtle(shape='circle')
    a.turtlesize(1)
    a.color('orange')
    a.penup()
    a.goto(-300,-155)
    a.pendown()
    a.stamp()
    a.penup()
    a.turtlesize(.30)
    a.goto(-330,-200)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(-275,-200)
    a.pendown()
    a.stamp()
    a.penup()
    a.goto(-300,-130)
    a.color("yellow")
    for i in range (5):
        a.pendown()
        a.begin_fill()
        a.circle(10)
    a.hideturtle()
    
def house():
    a=t.Turtle(shape='square')
    a.turtlesize(4)
    a.color('brown')
    a.penup()
    a.goto(300,-280)
    a.pendown()
    a.stamp()
    a.penup()
    a.turtlesize(1)
    a.color('black')
    a.goto(300,-300)
    a.pendown()
    a.stamp()
    a.penup()
    a=t.Turtle(shape='triangle')
    a.turtlesize(5)
    a.color('red')
    a.tilt(90)
    a.penup()
    a.goto(300,-220)
    a.pendown()
    a.stamp()
    a.penup()
    
def sun():
    a=t.Turtle(shape='circle')
    a.turtlesize(4)
    a.color("yellow")
    a.penup()
    a.goto(-350,280)
    a.pendown()
    a.stamp()
    a.penup()
    
def image():
    santa = "santa.jpg"
    wn.addshape(santa)
    a= t.Turtle()
    a.penup()
    a.goto(100,100)
    a.pendown()
    a.stamp()
    
    
present('orange','red')
trunkOfTree('brown')
tree('green',2)
ornaments()
star()
snowMan('white',2)
snowFace()
hat()
text()
angel()
house()
sun()
image()
snow(100,'white',-(wn.window_width()/2),(wn.window_width()/2),425,320,30,5,300)
wn.mainloop()
